### ISSUE TITLE
hello ,how can i do it?

### ISSUE THREAD

**Issue by mvwtest** [diegovazquez/ESPPlane#2]
In PlatformIO by VSCodium ,I build blink is worked.
But ,when build this project, I got this:
---------------------------------------------------------------------------------------------
src/Servo.h: In function 'void startServo()':
src/Servo.h:9:5: error: 'servo1' was not declared in this scope
    9 |     servo1.attach(SERVO1_PIN); // attaches the servo
      |     ^~~~~~
src/Servo.h:10:5: error: 'servo2' was not declared in this scope
   10 |     servo2.attach(SERVO2_PIN); // attaches the servo
      |     ^~~~~~
src/Servo.h:11:5: error: 'servo3' was not declared in this scope
   11 |     servo3.attach(SERVO3_PIN); // attaches the servo
      |     ^~~~~~
src/Servo.h:12:5: error: 'servo4' was not declared in this scope
   12 |     servo4.attach(SERVO4_PIN); // attaches the servo
---------------------------------------------------------------------------------------------
how can i do it? ,can you help me, I` m Davis. thank you.

**Comment by diegovazquez** [comment]
Hi Davis. Please see step 5 of "Install Firmware to ESP8266" in readme.md. SERVO1_PIN is declared in configuration.h

**Comment by diegovazquez** [comment]
@mvwtest , was your issue resolved?

**Comment by diegovazquez** [comment]
closed due to inactivity
